import { chromium } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-omnilearn/73c89a4a-ba3f-5180-a913-3be7e41fad79/scratchpad';
const base='http://localhost:4655';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1280,height:900}});
p.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text());});
p.on('response',r=>{if(r.url().includes('/api/')&&!r.ok())console.log('HTTP',r.status(),r.url());});
await p.goto(base+'/#/milestone/attention-from-scratch/multihead');
await p.waitForSelector('[data-testid="calibration"]',{timeout:20000});
const calib=await (await p.request.post(`${base}/api/projects/attention-from-scratch/calibration`,{data:{milestoneId:'multihead'}})).json();
console.log('questions',calib.questions.length);
const picks=calib.questions.map((q,i)=> i===0? q.answerIndex : q.options.length-1);
for(let i=0;i<picks.length;i++) await p.getByTestId(`calib-opt-${i}-${picks[i]}`).click();
await p.getByTestId('calib-submit').click();
await p.waitForTimeout(4000);
await p.screenshot({path:`${OUT}/dbg-after-submit.png`,fullPage:true});
console.log(await p.locator('[data-testid]').evaluateAll(els=>els.map(e=>e.dataset.testid).join(',')));
console.log(await p.locator('body').innerText());
await b.close();
