import { chromium, request as pwrequest } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-omnilearn/73c89a4a-ba3f-5180-a913-3be7e41fad79/scratchpad';
const base='http://localhost:4655';
const api = await pwrequest.newContext({ baseURL: base });
await api.delete('/api/projects/attention-from-scratch');
const plan = await (await api.post('/api/projects/plan',{data:{goal:'mhsa in numpy'}})).json();
await api.post('/api/projects',{data:plan});
const calib = await (await api.post('/api/projects/attention-from-scratch/calibration',{data:{milestoneId:'sdpa'}})).json();
const answers = calib.questions.map((q,i)=> i<2 ? q.answerIndex : -1);
await api.post('/api/projects/attention-from-scratch/calibration/submit',{data:{milestoneId:'sdpa',answers}});

const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1280,height:900}});
await p.goto(base+'/#/');
await p.waitForSelector('[data-testid="library"]');
await p.waitForTimeout(1200);
await p.screenshot({path:`${OUT}/A-library.png`});
await p.getByTestId('new-project').click();
await p.waitForTimeout(700);
await p.getByTestId('goal-input').fill('a byte-pair-encoding tokenizer, not from scratch — I can use regex');
await p.screenshot({path:`${OUT}/B-goal.png`});
await p.keyboard.press('Escape');
await p.goto(base+'/#/milestone/attention-from-scratch/sdpa');
await p.waitForSelector('[data-testid="primer-deck"]');
await p.waitForTimeout(1000);
await p.screenshot({path:`${OUT}/C-deck-story.png`,fullPage:true});
await p.locator('.story-scroll').evaluate(el=>{el.scrollTop=el.scrollHeight;});
await p.waitForTimeout(900);
await p.screenshot({path:`${OUT}/D-story-end.png`,fullPage:true});
await p.getByTestId('primer-next').click();
await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/E-card.png`,fullPage:true});
await p.getByTestId('primer-next').click();
await p.waitForTimeout(500);
await p.getByTestId('check-opt-1').click();
await p.waitForTimeout(600);
await p.screenshot({path:`${OUT}/F-check.png`,fullPage:true});
await b.close();
