import { chromium, request as pwrequest } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-omnilearn/73c89a4a-ba3f-5180-a913-3be7e41fad79/scratchpad';
const base='http://localhost:4655';
const api = await pwrequest.newContext({ baseURL: base });
await api.put('/api/settings',{data:{scheme:'arcade'}});
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1280,height:900}});
await p.goto(base+'/#/');
await p.waitForTimeout(1600);
await p.screenshot({path:`${OUT}/L-arcade-library.png`});
await p.goto(base+'/#/milestone/attention-from-scratch/multihead');
await p.waitForSelector('[data-testid="primer-deck"]');
await p.waitForTimeout(1500);
await p.screenshot({path:`${OUT}/M-arcade-deck.png`,fullPage:true});
await api.put('/api/settings',{data:{scheme:'blackboard'}});
await p.goto(base+'/#/milestone/attention-from-scratch/multihead');
await p.waitForSelector('[data-testid="primer-deck"]');
await p.waitForTimeout(1500);
await p.getByTestId('primer-next').click();
await p.waitForTimeout(400);
await p.getByTestId('check-opt-0').click();
await p.waitForTimeout(1600);
await p.screenshot({path:`${OUT}/N-blackboard-finish.png`,fullPage:true});
await b.close();
