import { chromium, request as pwrequest } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-omnilearn/73c89a4a-ba3f-5180-a913-3be7e41fad79/scratchpad';
const base='http://localhost:4655';
const api = await pwrequest.newContext({ baseURL: base });
await api.put('/api/settings',{data:{scheme:'blackboard'}});
await api.delete('/api/projects/attention-from-scratch');
const plan = await (await api.post('/api/projects/plan',{data:{goal:'mhsa in numpy'}})).json();
await api.post('/api/projects',{data:plan});
const calib = await (await api.post('/api/projects/attention-from-scratch/calibration',{data:{milestoneId:'sdpa'}})).json();
await api.post('/api/projects/attention-from-scratch/calibration/submit',{data:{milestoneId:'sdpa',answers:calib.questions.map((q,i)=>i<2?q.answerIndex:-1)}});
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1280,height:900}});
await p.goto(base+'/#/milestone/attention-from-scratch/sdpa');
await p.waitForSelector('[data-testid="primer-deck"]');
await p.waitForTimeout(1500);
await p.screenshot({path:`${OUT}/O-blackboard-deck.png`,fullPage:true});
await p.setViewportSize({width:520,height:820});
await p.waitForTimeout(800);
await p.screenshot({path:`${OUT}/P-narrow.png`,fullPage:true});
await b.close();
