import { chromium, request as pwrequest } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-omnilearn/73c89a4a-ba3f-5180-a913-3be7e41fad79/scratchpad';
const base='http://localhost:4655';
const api = await pwrequest.newContext({ baseURL: base });
await api.put('/api/settings',{data:{scheme:'sunshower'}});
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1280,height:1000}});
await p.goto(base+'/#/milestone/attention-from-scratch/multihead');
await p.waitForSelector('[data-testid="calibration"]');
await p.waitForTimeout(1500);
await p.screenshot({path:`${OUT}/G-calib-sunshower.png`,fullPage:true});
await p.getByTestId('calib-opt-0-0').click();
await p.getByTestId('calib-opt-1-3').click();
await p.waitForTimeout(600);
await p.screenshot({path:`${OUT}/H-calib-picked.png`,fullPage:true});
await p.getByTestId('calib-submit').click();
await p.waitForSelector('[data-testid="primer-deck"]');
await p.waitForTimeout(1500);
await p.screenshot({path:`${OUT}/I-deck-with-summary.png`,fullPage:true});
await api.put('/api/settings',{data:{scheme:'mint'}});
await p.reload();
await p.waitForTimeout(1800);
await p.screenshot({path:`${OUT}/J-mint-deck.png`,fullPage:true});
await api.put('/api/settings',{data:{scheme:'blackboard'}});
await p.goto(base+'/#/');
await p.waitForTimeout(1500);
await p.getByTestId('settings').click();
await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/K-blackboard-settings.png`});
await b.close();
